### ISSUE TITLE
Consider using package.json `engines` instead of checking for node version in index.js

### ISSUE THREAD

**Issue by filmaj** [adobe/create-whisk-action#1]
Was just a thought ? Perhaps easier than implementing our own version checking?

https://docs.npmjs.com/files/package.json#engines

**Comment by macdonst** [comment]
@filmaj from the docs:

> Unless the user has set the engine-strict config flag, this field is advisory only and will only produce warnings when your package is installed as a dependency.

and `engines-strict` was removed in npm 3.0.0. 

I did a quick test using the engines property and specifying node >= 12 and the package still installed. So I think we are stuck with the way it works now unless I'm missing something.

**Comment by filmaj** [comment]
Well, then, crap. Closing this down.
